# Site settings
title: The Exciting World of Programming
header-img: img/home-bg.png
email: mnj.webdeveloper@gmail.com
copyright_name: marcnjaramillo
description: > # this means to ignore newlines until "baseurl:"
  Creating Awesome User Experiences
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  marcnjaramillo
learn_profile: marcnjaramillo
email_username: mnj.webdeveloper@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
